# 월드 초기화 (단위 : 1일)
world_reset_activate: false
world_reset_interval: 1
world_reset_last_date: 20250510 030000

# 서버 자동 종료
server_auto_stop_activate: false
server_auto_stop_time: 01:00:00

# 청소 주기 (단위 : 분)
clean_activate: false
clean_interval: 30

# 부자 동상 생성 주기 (단위 : 일)
wealthy_statue_create_activate: false
wealthy_statue_create_interval: 1
wealthy_statue_create_last_date: 20250520 030000
wealthy_statue_create_locations: {}
wealthy_statue_create_ids: {}

# 정각 타종음
church_bell_sound_activate: false
church_bell_sound_location: {}
church_bell_sound_name: sepia_film_sounds:sound_effect.tower_bell
church_bell_sound_volume: 10.0
church_bell_sound_length: 2

# 이동권 주기 (단위 : 분)
wild_warp_ticket_interval: 30
hell_warp_ticket_interval: 30

# 이동권 남은 시간
remaining_time: {}